### PR TITLE
Added sqlite jdbc driver lib to the repo.

### PR DESCRIPTION
**Pull request by pavog**
Added JSON and SQLite to the output jar (Release 2.7.1).
I also updated the plugin.yml version to 2.7.1 (New API + Fixed SQLite backend).

### CODE REVIEW

**Comment by pavog** [comment]
Please merge this. The people need it in order to use the (default) sqlite adapter.

**Comment by vincidev** [comment]
I will soon upload a totally changed bungeeban though. Working and new.

**Comment by pavog** [comment]
Sounds good!

**Comment by vincidev** [comment]
:) I am currently doing an own simply database server for the plugin, but I am affraid some hosters dont allow opening another port. So I will do a workaround for them.

**Comment by pavog** [comment]
Sounds really good. I'm definitly looking forward to the release :)
It you need any help (programming or documentation / wiki wise) let me know!

**Comment by vincidev** [comment]
Thanks mate.

**Pull request merged**
