### PR TITLE
Updated PlayerUtil to be more efficient

### PR DESCRIPTION
**Pull request by ImNatho**
- Changed PlayerUtil to use less memory and prevent memory leaks.
- Made the cache more efficient by combining it into tow methods and one
Map<>.
- Updated other classes to use updated PlayerUtils.
- Corrected incorrect camel case method names in PlayerUtils.
- Added JavaDocs to PlayerUtils.

### CODE REVIEW

**Comment by ImNatho** [comment]
This change just makes the PlayerUtil use less bandwidth and stops a possible memory leak for servers that do not restart at any point.

I might add a cache expiry to further prevent memory leaks.

**Comment by vincidev** [comment]
Thanks for putting such a huge effort in helping me. I was busy with school currently and could thus not put a lot of time into coding. I will update the plugin soon.

**Comment by ImNatho** [comment]
Ok, No worries. Just make sure you import gson into your ide.

**Comment by vincidev** [comment]
I will. Expect me to update it on the weekend :)

**Pull request merged**
